/* eslint-disable quote-props */
const shipColor = [0.97, 0.98, 1];

const monster = {
	blocked: 1,
	renderAs: 'billboard',
	npc: 'monster',
	faction: 'monsters',
	aggro: 1,
};

export default {
	// music: 'forest',
	// ambience: 'darkForest',
	ambientLightIntensity: 0.4,
	legend: {
		' ': {
			name: 'empty',
			blocked: 0,
			renderAs: false,
		},
		'.': {
			name: 'void',
			blocked: 1,
			renderAs: false,
		},
		'H': {
			name: 'ship hull',
			blocked: 1,
			renderAs: 'box',
			color: shipColor,
			texture: 'shipwall.png',
			textureRange: [8, 15],
		},
		'W': {
			name: 'ship window',
			blocked: 1,
			renderAs: 'box',
			color: shipColor,
			texture: 'ship_window.png',
		},
		'F': {
			name: 'ship floor',
			blocked: 1,
			renderAs: 'box',
			color: shipColor,
			texture: 'shipwall.png',
			textureRange: [0, 7],
		},
		'T': {
			name: 'ship pillar',
			blocked: 1,
			renderAs: 'box',
			color: shipColor,
			texture: 'shipwall.png',
			textureRange: [8, 15],
			size: [0.75, 0.75, 1],
		},
		'|': {
			name: 'pipes',
			blocked: 1,
			renderAs: 'billboard',
			color: shipColor,
			texture: 'pipes.png',
			interact: {
				outcome: {
					text: 'You turn the wheel and you hear gears clank throughout the ship. The door is now unlocked.',
					blockChange: { id: 'ship-door', blocked: 0 },
				},
			},
		},
		'I': {
			name: 'pipes',
			blocked: 1,
			renderAs: 'billboard',
			color: shipColor,
			texture: 'pipes_wheel.png',
		},
		'+': {
			id: 'ship-door',
			name: 'door',
			blocked: 0,
			renderAs: 'box',
			color: shipColor,
			texture: 'ship_door.png',
			// textureRange: [0, 3],
			interact: {
				outcome: {
					text: 'The door is unlocked somewhere else.',
				},
			},
		},
		'&': {
			name: 'cave',
			blocked: 1,
			renderAs: 'box',
			color: [0.9, 0.9, 0.9],
			texture: 'cave.png',
			// textureRange: [0, 3],
		},
		'S': {
			name: 'secret cave',
			blocked: 1,
			renderAs: 'box',
			color: [1, 0.9, 0.9],
			texture: 'cave_crack.png',
			// textureRange: [0, 3],
		},
		'C': {
			...monster,
			name: 'chomper',
			texture: 'chomper.png',
			// textureRange: [0, 3],
		},
		'B': {
			...monster,
			name: 'monstrosity',
			npc: 'still',
			aggro: 0,
			texture: 'skull_blob.png',
			textureRange: [0, 1],
		},
		// Event Triggers
		'1': {
			name: 'The Voice',
			blocked: 0,
			renderAs: 'billboard',
			faction: 'loyalist',
			texture: 'voice.png',
			light: [1, 2],
			npc: 'still',
			aggro: 0,
			trigger: {
				talk: true,
			},
			dialog: {
				where: {
					q: 'Where am I?',
					a: 'Glad you\'re finally awake. Your memory really didn\'t fare well after such a sleep, did it?',
					unlocks: 'sleep',
				},
				who: {
					q: 'Who are you?',
					a: 'I\'m your... guide. I navigated this ship, wacthing the Void, while you slept. For eons perhaps.',
					unlocks: ['eons', 'sleep', 'ship'],
				},
				sleep: {
					locked: true,
					q: 'I\'ve been asleep?',
					a: 'You\'ve been asleep here, on our mining ship. I\'ve just docked her onto this asteroid and started the process of waking you.',
					unlocks: ['ship', 'mining', 'asteroid'],
				},
				eons: {
					locked: true,
					q: 'Eons?',
					a: 'We\'re a very long way from the Seat of the Endless Kingdom. But our mission is important.',
					unlocks: ['mission', 'kingdom'],
				},
				mission: {
					locked: true,
					q: 'What mission?',
					a: 'You\'re here to mine this asteroid - with my help. It beats staring out the window, going mad looking into the endless Void.',
					unlocks: ['asteroid', 'mining'],
				},
				kingdom: {
					locked: true,
					q: 'Kingdom?',
					a: 'This expedition was put together by The Endless Intellect, King of A Thousand Suns, himself. We are fortunate to be here.',
				},
				ship: {
					locked: true,
					q: 'This is a ship?',
					a: 'It\'s small, rusty, the steam compressor is old, and the aethereal engine isn\'t the fastest, but it\'s capable for mining.',
					unlocks: ['mining'],
				},
				mining: {
					locked: true,
					q: 'Mining?',
					a: 'That\'s what we\'re here for: mining this asteroid. You have a plasma mining rifle that\'s well suited for the job.',
				},
				asteroid: {
					locked: true,
					q: 'So we\'re on an asteroid?',
					a: 'I\'ve docked with the asteroid, right onto a small cave dug out by a star worm. You can head out the door as soon as you\'re ready.',
				},
			},
		},
	},
	map: [
		[
			'                   ',
			'          &&&&&&&& ',
			'FFFFFFF  &&&&&&&&&&',
			'FFFFFFF&&&&&&&&&&&&',
			'FFFFFFF&&&&&&&&&&&&',
			'FFFFFHF&&&&&&&&&&&&',
			'FFFFFFF&&&&&&&&&&&&',
			'FFFFFFF&&&&&&&&&&&&',
			'FFFFFFF&&&&&&&&&&&&',
			'FFFFFFF&&&&&&&&&&&&',
			'FFFFFFF &&&&&&&&&&&',
			'         &&&&&&&&&&',
			'          &&&&&&&&&',
			'           &&&&&&&&',
		],
		[
			'            &&  .  ',
			' HWWWH    &&&&&& & ',
			'HH   HH  &&&     & ',
			'H  1  H&&&&&  &  & ',
			'H|   IH&&&&&  &  & ',
			'WB    +      C&  &&',
			'H     H       &   +',
			'H T T H&&&&&&S&&&&&',
			'H H H H&& &&& && &&',
			'H H|H H&&&&&& && &&',
			'HHHHHHH &&&&& &&&&&',
			' H   H   &&&& &&&&&',
			'          &&&     +',
			'           &&&&&&&&',
		],
		[
			'                   ',
			' HHHHH    &&&&&&&& ',
			'F|TTT|F  &&&&&&&&&&',
			'H     H&&&&&&&&&&&&',
			'HT   TH&&&&&&&&&&&&',
			'H     H&&&&&&&&&&&&',
			'H     H&&&&&&&&&&&&',
			'FFTFTFF&&&&&&&&&&&&',
			'FFFFFFF&&&&&&&&&&&&',
			'FFFFFFF&&&&&&&&&&&&',
			'FFFFFFF &&&&&&&&&&&',
			'         &&&&&&&&&&',
			'          &&&&&&&&&',
			'           &&&&&&&&',
		],
		[
			'                   ',
			'          &&&&&&&& ',
			'FFFHFFF  &&&&&&&&&&',
			'FFFHFFF&&&&&&&&&&&&',
			'FFFHFFF&&&&&&&&&&&&',
			'FFFHFFF&&&&&&&&&&&&',
			'FFFHFFF&&&&&&&&&&&&',
			'FFFFFFF&&&&&&&&&&&&',
			'FFFFFFF&&&&&&&&&&&&',
			'FFFFFFF&&&&&&&&&&&&',
			'FFFFFFF &&&&&&&&&&&',
			'         &&&&&&&&&&',
			'          &&&&&&&&&',
			'           &&&&&&&&',
		],
	],
};
