/* eslint-disable quote-props */
import { shipColor, caveColor, teleportDoor, monster, voice, baseLegend } from './baseLegend.js';

export default {
	// music: 'forest',
	// ambience: 'darkForest',
	ambientLightIntensity: 0.4,
	legend: {
		...baseLegend,
		'H': {
			name: 'ship hull',
			blocked: 1,
			renderAs: 'box',
			color: shipColor,
			texture: 'shipwall.png',
			textureRange: [8, 15],
		},
		'W': {
			name: 'ship window',
			blocked: 1,
			renderAs: 'box',
			color: shipColor,
			texture: 'ship_window.png',
		},
		'F': {
			name: 'ship floor',
			blocked: 1,
			renderAs: 'box',
			color: shipColor,
			texture: 'shipwall.png',
			textureRange: [0, 7],
		},
		'T': {
			name: 'ship pillar',
			blocked: 1,
			renderAs: 'box',
			color: shipColor,
			texture: 'shipwall.png',
			textureRange: [8, 15],
			size: [0.75, 0.75, 1],
		},
		'|': {
			name: 'pipes',
			blocked: 1,
			renderAs: 'billboard',
			color: shipColor,
			texture: 'pipes.png',
			interact: {
				outcome: {
					text: 'You turn the wheel and you hear gears clank throughout the ship. The door is now unlocked.',
					blockChange: { id: 'ship-door', blocked: 0 },
				},
			},
		},
		'I': {
			name: 'pipes',
			blocked: 1,
			renderAs: 'billboard',
			color: shipColor,
			texture: 'pipes_wheel.png',
		},
		'+': {
			id: 'ship-door',
			name: 'door',
			blocked: 0,
			renderAs: 'box',
			color: shipColor,
			texture: 'ship_door.png',
			// textureRange: [0, 3],
			interact: {
				outcome: { text: 'The door is unlocked somewhere else.' },
				//
			},
		},
		'&': {
			name: 'cave',
			blocked: 1,
			renderAs: 'box',
			color: caveColor,
			texture: 'cave.png',
			// textureRange: [0, 3],
		},
		'S': {
			name: 'secret cave',
			blocked: 1,
			renderAs: 'box',
			color: caveColor,
			texture: 'cave_crack.png',
			// textureRange: [0, 3],
		},
		'X': {
			name: 'destrucible cave wall',
			blocked: 1,
			renderAs: 'box',
			npc: 'mindless',
			color: caveColor,
			texture: 'cave_crack.png',
			// textureRange: [0, 3],
		},
		'C': {
			...monster,
			name: 'chomper',
			texture: 'chomper.png',
			// textureRange: [0, 3],
		},
		// Event Triggers
		'1': {
			...voice,
			dialog: {
			},
		},
		'>': {
			...teleportDoor,
			texture: 'cavehole.png',
			// teleport: ['templeMap', 1, 12, 1, 0],
		},
		'<': {
			...teleportDoor,
			texture: 'cavehole.png',
			teleport: ['templeMap', 1, 12, 1, 0],
		},
	},
	map: [
		[
			'                   ',
			'          &&&&&&&& ',
			'FFFFFFF  &&&&&&&&&&',
			'FFFFFFF&&&&&&&&&&&&',
			'FFFFFFF&&&&&&&&&&&&',
			'FFFFFHF&&&&&&&&&&&&',
			'FFFFFFF&&&&&&&&&&&&',
			'FFFFFFF&&&&&&&&&&&&',
			'FFFFFFF&&&&&&&&&&&&',
			'FFFFFFF&&&&&&&&&&&&',
			'FFFFFFF &&&&&&&&&&&',
			'         &&&&&&&&&&',
			'          &&&&&&&&&',
			'           &&&&&&&&',
		],
		[
			'            &&&&&& ',
			' HWWWH    &&&  &&& ',
			'HH   HH  &&&     & ',
			'H     H&&&&&  &  & ',
			'H|   IH&&&&&  &  (&',
			'W 1   +       &X((&',
			'H     H       &  (&',
			'H T T H&&&&&&X&&&>&',
			'H H H H&& &&& && &&',
			'H H|H H&&&&&& && &&',
			'HHHHHHH &&&&& &&&&&',
			' H   H   &&&& &&&&&',
			'          &&&     <',
			'           &&&&&&&&',
		],
		[
			'                   ',
			' HHHHH    &&&&&&&& ',
			'F|TTT|F  &&&&&&&&&&',
			'H     H&&&&&&&&&&&&',
			'HT   TH&&&&&&&&&&&&',
			'H     H&&&&&&&&&&&&',
			'H     H&&&&&&&&&&&&',
			'FFTFTFF&&&&&&&&&&&&',
			'FFFFFFF&&&&&&&&&&&&',
			'FFFFFFF&&&&&&&&&&&&',
			'FFFFFFF &&&&&&&&&&&',
			'         &&&&&&&&&&',
			'          &&&&&&&&&',
			'           &&&&&&&&',
		],
		[
			'                   ',
			'          &&&&&&&& ',
			'FFFHFFF  &&&&&&&&&&',
			'FFFHFFF&&&&&&&&&&&&',
			'FFFHFFF&&&&&&&&&&&&',
			'FFFHFFF&&&&&&&&&&&&',
			'FFFHFFF&&&&&&&&&&&&',
			'FFFFFFF&&&&&&&&&&&&',
			'FFFFFFF&&&&&&&&&&&&',
			'FFFFFFF&&&&&&&&&&&&',
			'FFFFFFF &&&&&&&&&&&',
			'         &&&&&&&&&&',
			'          &&&&&&&&&',
			'           &&&&&&&&',
		],
	],
};
