import legend from './legend.js';

export default {
	temple: {
			legend,
			map: [
				[
					'###################',
					'###################',
					'###### #&&#########',
					'###################',
					'###################',
					'###################',
					'########## ########',
				],
				[
					'##########1########',
					'###    &&| | #    #',
					'#   #         && # ',
					'# # #       && &#C#',
					'### ###C    && &  #',
					'###   ###         #',
					'#########&3&&######',
				],
				[
					'##########2       #',
					'################# #',
					'######&&&& ########',
					'########## ########',
					'###        ## #### ',
					'###   ####     ####',
					'#########& ########',
				],
			],
		},
	forest: {
		legend,
		map: [
			[
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'ddddddddddddddddddddoOoddddddddd',
				// 'dddddddddddddddddddddodddddddddd',
				// 'dddddddddddddddddddddodddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				// 'dddddddddddddddddddddddddddddddd',
				'ddddddddddddddddddddd',
				'ddddddddddddddddddddd',
				'dddddddddoOoddddddddd',
				'ddddddddddooddddddddd',
				'ddddddddddooddddddddd',
				'ddddddddddddddddddddd',
				'ddddddddddddddddddddd',
				'ddddddddddddddddddddd',
				'ddddddddddddddddddddd',
				'ddddddddddddddddddddd',
				'ddddddddddddddddddddd',
				'ddddddddddddddddddddd',
				'ddddddddddddddddddddd',
				'ddddddddddddddddddddd',
				'ddddddddddddddddddddd',
			],
			[
				// 'tttttttttttttttttttttttttttttttt',
				// 't                              t',
				// 't                              t',
				// 't                              t',
				// 't                              t',
				// 't                              t',
				// 't                              t',
				// 't                              t',
				// 't                              t',
				// 't                              t',
				// 't                              t',
				// 't                              t',
				// 't                              t',
				// 't                              t',
				// 't                              t',
				// 't                              t',
				// 't                              t',
				// 't                              t',
				// 't                              t',
				// 't                              t',
				// 't                              t',
				// 't                              t',
				// 't                              t',
				// 't                              t',
				// 't                              t',
				// 't                              t',
				// 't                   BfB        t',
				// 't                   oOo        t',
				// 't                    o         t',
				// 't                    o         t',
				// 't                              t',
				// 't                 t    t       t',
				// 't                 t   }t       t',
				// 't                 t[  ]t       t',
				// 't                 t|  |t       t',
				// 't                 t|  |t       t',
				// 't                 t    t       t',
				// 't                tt    tt      t',
				// 't                ta    ct      t',
				'tttttttttttttttttttt',
				't    y   BfB       t',
				't r           y    t',
				't   y  r     r     t',
				't         y        t',
				't              y   t',
				't    r  t   t      t',
				't  y    t  }t      t',
				't  r    t[ ]t      t',
				't       t| |t      t',
				't       t| |t      t',
				't       ta ct      t',
				't      t     t     t',
				't      t     t     t',
				'tttttttttttttttttttt',
			],
			[
				'                    ',
				'                    ',
				'                    ',
				'                    ',
				'                    ',
				'                    ',
				'                    ',
				'                    ',
				'                    ',
				'                    ',
				'                    ',
				'                    ',
				'                    ',
				'                    ',
				'                    ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
				// '                                ',
			],
		],
	},
	arena: {
		legend, // Note that not all maps need to use the same legend, they can be different
		map: [
			[ // Right now its best to have the "floor" levels be completely filled in
				'###################',
				'###################',
				'###################',
				'###################',
				'###################',
				'###################',
				'###################',
			],
			[
				' #########4####### ',
				'##|             |##',
				'#   C             #',
				'# # C          ##C#',
				'### C          #  #',
				'###      C   C   ##',
				' ################# ',
			],
			[
				' ################# ',
				'###################',
				'#                 #',
				'#                 #',
				'#                 #',
				'#                 #',
				' ################# ',
			],
		],
	},
};
