import legend from './legend.js';

export default {
	town: {
		music: 'forest',
		ambience: 'darkForest',
		legend,
		map: [
			[
				'                   ',
				'GGG&GGGGGGGGGGGGGGG',
				'GGG&GGGGGGGGGGGGGGG',
				'GGG&&&&&&&&&GGGGGGG',
				'GGGGGGG&GGGGGGGGGGG',
				'GGGGGGG&GGGGGGGGGGG',
				'GG&&GGG&GGGGGGGGGGG',
				'GG&&GGG&GGGGGGGGGGG',
				'GG&&&&&&GGGGGGGGGGG',
				'GG&&GGG&&&&&&&GGGGG',
				'GG&&GGG&GGGGGGGGGGG',
				'GG&&&&G&GGGGGGGGGGG',
				'GGGGGGG&GGGGGGGGGGG',
				'GGGGGGG&GGGGGGGGGGG',
			],
			[
				'###D###############',
				'### ###############',
				'#^       d T   T  #',
				'T                 T',
				'T b       ####    T',
				'T ####^e  #  #T   T',
				'T #  #   T#  ##   T',
				'T ##+#^   #   #   T',
				'T   a   c #+###   T',
				'T         | |     T',
				'GT            T  TG',
				'GT  f   ^  T     TG',
				'TTTTTT#1#TTTTTTTTTT',
				'GGTTTT# #TTGGTTTTGG',
			],
			[
				'# ###              ',
				'# ### # #^# # # # #',
				'#                 ^',
				'                   ',
				'           ^       ',
				'  ####    ####     ',
				'  #  #    #  #     ',
				'  ####    #  #     ',
				'          #  #     ',
				'          ####     ',
				'                   ',
				'T                  ',
				'      ###          ',
				'TT    # #   T    TT',
			],
		],
	},
	forest: {
		music: 'forest',
		ambience: 'darkForest',
		legend,
		map: [
			[
				'GGGGG&GGGGG',
				'GGGGG&GGGGG',
				'GGGGG&GGGGG',
				'GGGGG&GGGGG',
				'GGGGG&GGGGG',
				'GGGGG&GGGGG',
				'GGGGG&GGGGG',
				'GGGGG&GGGGG',
				'GGGGG&GGGGG',
			],
			[
				'GTTT#2#TTTG',
				'GTTT^  TTTG',
				'GTTT   TTTG',
				'GTTT    TTG',
				'GTTT   TTTG',
				'GTT    TTTG',
				'&TTT    TTG',
				'&TTT   TTTG',
				'&&&&&3&&&&&',
			],
			[
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'G          ',
				'&&  &&& &  ',
				'&&&&&&&&&&&',
			],
			[
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'G          ',
				'&&         ',
				'&&&&&&&&&& ',
			],
		],
	},
	fortress: {
		music: 'dungeon',
		ambience: 'spooky',
		legend,
		map: [
			[
				'################&&&',
				'###############&&&&',
				'######&#&&#####&&&&',
				'################&&&',
				'###############&&&&',
				'##&&###########&&&&',
				'##&&############&&&',
				'##&&#############&&',
				'##&&#############&&',
				'##&&#############&&',
				'##&&&&#############',
				'########## ########',
			],
			[
				'##########5###&&4&&',
				'# #    &&| |^#&   &',
				'#   #         &&  &',
				'# & #^     g&& & O&',
				'# &###p &&&&&& &  &',
				'# #  ###   ^   &  &',
				'& #          # &  &',
				'& # #####      #  &',
				'& #    #      #   &',
				'& # # ####    ## ##',
				'#  C   #          #',
				'#&&&&&###&&&&###&&&',
			],
			[
				'##########        #',
				'###############&&&&',
				'######&&&& ####&&&&',
				'########## ####&&&&',
				'###  &&#    ## && &',
				'###   ####   &&&&&&',
				'###   ####    #####',
				'##########    #####',
				'#&&&&&####    #####',
				'#########     #####',
				'###   ###         #',
				'#########& ########',
			],
			[
				'##############&&&&&',
				'#      &&    #&    ',
				'#   #         &&   ',
				'#   #       && &&&&',
				'# &###  &&&&&& &&&&',
				'# #  ###       &  &',
				'& #          # &  &',
				'& # #####      #  &',
				'& #    #########   &',
				'& # # ####    ## ##',
				'#      #          #',
				'#&&&&&###&&&&###&&&',
			],
		}
	temple: {
			legend,
			map: [
				[
					'###################',
					'###################',
					'###### #&&#########',
					'###################',
					'###################',
					'###################',
					'########## ########',
				],
				[
					'##########1########',
					'###    &&| | #    #',
					'#   #         && # ',
					'# # #       && &#C#',
					'### ###C    && &  #',
					'###   ###         #',
					'#########&3&&######',
				],
				[
					'##########2       #',
					'################# #',
					'######&&&& ########',
					'########## ########',
					'###        ## #### ',
					'###   ####     ####',
					'#########& ########',
				],
			],
		},
	forest: {
		legend,
		map: [
			[
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'ddddddddddddddddddddoddddddddddd',
				'dddddddddddddddddddoOodddddddddd',
				'dddddddddddddddddddoOodddddddddd',
				'ddddddddddddddddddddoddddddddddd',
				'ddddddddddddddddddddoddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
				'dddddddddddddddddddddddddddddddd',
			],
			[
				'mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                  BfB         m',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                              m',
				'm                 t   t        m',
				'm                 t  }t        m',
				'm                 t[ ]t        m',
				'm                 t| ]t        m',
				'm                 t| ]t        m',
				'm                 ta ct        m',
				'm                tt    tt      m',
				'm                t      t      m',
				'mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm',
			],
			[
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
				'                                ',
			],
		],
	},
	tavern: {
		music: 'tavern',
		ambience: 'spooky',
		legend, // Note that not all maps need to use the same legend, they can be different
		map: [
			[ // Right now its best to have the "floor" levels be completely filled in
				'###################',
				'###################',
				'###################',
				'###################',
				'###################',
				'&&&&&&#############',
				'&&#################',
			],
			[
				' &&&&&############ ',
				'####      ^      |#',
				'####C #^          #',
				'####  #        ## #',
				'##7#  #^          #',
				'&     #| O^  |   |#',
				' &&&&& ########6## ',
			],
			[
				'                   ',
				' ##   #############',
				'####  #          ##',
				'####           #^##',
				' ##   #          ##',
				'      #############',
				' #####             ',
			],
			[
				'                   ',
				' ##                ',
				'#  #  #############',
				'#  #           #   ',
				' ##   #############',
				'                   ',
				'                   ',
			],
			[
				'                   ',
				' ##                ',
				'#  #               ',
				'#  #  #############',
				' ##                ',
				'                   ',
				'                   ',
			],
		],
	},
	tower1: {
		music: 'dungeon',
		ambience: 'spooky',
		legend,
		map: [
			[
				'###################',
				'###################',
				'###################',
				'###################',
				'###################',
				'###################',
				'###################',
			],
			[
				' ###8########9#### ',
				'#### ######## #####',
				'#                 #',
				'#                 #',
				'#                 #',
				'#                 #',
				' #################',
			],
			[
				'###################',
				'###################',
				'###################',
				'###################',
				'###################',
				'###################',
				'###################',
			],
		],
	},
	tower2: {
		music: 'boss',
		ambience: 'spooky',
		legend,
		map: [
			[
				'###################',
				'###################',
				'###################',
				'###################',
				'###################',
				'###################',
				'###################',
			],
			[
				' #############0### ',
				'#            # #  #',
				'##   |||   |||    #',
				'#                ^#',
				'##   |||   |||    #',
				'#                 #',
				' ################# ',
			],
			[
				' ############# ### ',
				'#            ###  #',
				'#^                #',
				'#                 #',
				'#^                #',
				'#                 #',
				' ################# ',
			],
			[
				' ################# ',
				'#                 #',
				'##                #',
				'#                 #',
				'##                #',
				'#                 #',
				' ################# ',
			],
			[
				' ################# ',
				'###################',
				'###################',
				'###################',
				'###################',
				'###################',
				' ################# ',
			],
		],
	},
};
